### ISSUE TITLE
Browse hidden apps

### ISSUE THREAD

**Issue by Donkey-Doug** [jkuester/unlauncher#103]
Make it possible to browse the hidden apps without unhiding them.

**Comment by Charles7z** [comment]
I would assume that donkey wants to show those apps he's unchecked in the customize drawer..... To clean up the app drawer.

A simple show/hide icon in the search field of the app drawer that toggles showing or hiding those unchecked apps would be very user friendly.

**Comment by egyfeny** [comment]
Yes, browse hidden apps was just what I wanted to suggest ;⁠)  Another simple solution could be, that apps not shown in drawer are findable with the search instead. Perhaps this is not to hard to implement?

**Comment by Donkey-Doug** [comment]
Yes, make apps hidden in "Customize Drawer" options  findable with search.
