### ISSUE TITLE
New selection option for menu item "Change appearance"

### ISSUE THREAD

**Issue by tuch96** [jkuester/unlauncher#104]
Hi @jkuester ,

Is it possible to integrate a function in the "Change Appearance" setting that adopts the respective set system standard for "Dark Mode"?

I also use the schedule for automatic activation and deactivation of the dark mode in the system settings. If the launcher were linked to the system setting, it would also adapt automatically.

I came across the launcher at F-Droid and find the minimalist approach terrific! Works very well under LineageOS 18.1 and Android 12.

Many thanks and best regards

**Comment by jkuester** [comment]
@tuch96 thank you for the kind words and encouragement!  This is definitely a feature we would like to have. (See #67 and #9)  

At this point it is just waiting on someone to implement it.
