### ISSUE TITLE
Request: support apps from work profile (via Shelter)

### ISSUE THREAD

**Issue by os-i-am** [jkuester/unlauncher#11]
Great launcher, thanks a lot!
One issue I ran into: I use shelter (https://github.com/PeterCxy/Shelter) to put serveral apps from Aurora (Google Play) Store into a "work" profile in order to keep them seperated from "personal" F-Droid apps. These "sheltered" apps can't be selected from the list of apps for pinning them to the launch screen. Can you do anything about it?

**Comment by mikae1** [comment]
> These "sheltered" apps can't be selected from the list of apps for pinning them to the launch screen.

Also, they can not even be launched. I see them if I tap "Apps" to see all apps. They're at the bottom of the list prefixed with "W". However, if I tap any of these apps, nothing happens.

**Comment by dnaod** [comment]
I came to share a similar experience, although my work profile apps are installed directly from the Google Play app store.

Apps which are not installed on the personal profile, launch correctly.  But apps that are installed in both the personal and work profiles have consistent but undefined behaviour depending on the apps.

Some examples of behaviours observed when an app is installed in both the work and personal profiles and launched from the apps list:
- Slack: Doesn't launch at all
- Google Calendar: Launches the app from the personal profile

**Comment by TobiTenno** [comment]
For standard work profile apps (like from Microsoft Intune), I'm able to launch them. Might've been fixed upstream?

**Comment by dnaod** [comment]
To trigger the bug(s), you must have the app installed in both your personal and work profiles.  If it's only installed in your work profile, it will work as expected.

**Comment by koppen37** [comment]
@jkuester I think this bug should be fixed once you update 
https://github.com/jkuester/unlauncher/blob/912e48f6785367a55a607d57e6ff06b3f5986334/app/src/main/java/com/sduduzog/slimlauncher/ui/options/OpenAppsFragment.kt#L10
to use the new way to launch apps, as defined in
 https://github.com/jkuester/unlauncher/blob/912e48f6785367a55a607d57e6ff06b3f5986334/app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt#L143

**Comment by jkuester** [comment]
Okay, I finally got around to testing this to verify that it is, in fact, fixed.  I am able (using Shelter) to open apps that I cloned into my shelter as well as apps that are only installed in the shelter.  Also, I confirmed that when I open a cloned app, it is actually a new version of the app and not just my un-sheltered version that is opened.

If someone on the latest version of Unlauncher is still experiencing issues with this functionality, feel free to re-open this issue.
