### ISSUE TITLE
Add the possibility to use custom date format

### ISSUE THREAD

**Issue by milouse** [jkuester/unlauncher#117]
Hi,

I already made some research and found the two previous issues #33 and #39.

However, my request for enhancement here is a bit different.

I don’t know for other countries, but at least in France/french, the current date format sounds very weird. Currently, [the code](https://github.com/jkuester/unlauncher/blob/master/app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt#L229) reads as 

```kotlin
val fWatchDate = SimpleDateFormat("EEE, MMM dd", currentLocale)
```

In french, it will be correctly expanded (thanks to the `currentLocale` thing I assume) to **mer., juin 29**. So yes, that’s correctly translated, but nobody in french use that date format. Instead we prefer things like **mer. 29  juin**

My proposal here, is to variabilize the `"EEE, MMM dd"` string and either add it in the strings.xml file to let each translator use the best format for their language, or to add a new option and let the end-user either choose between some pre-selectioned format, or let him enter directly the format string of their wish (in my case `EEE dd MMM` for exemple).

I never ever do any kotlin/android code before, but if necessary I can try to work on that if you want?

Thank you very much.

**Comment by jkuester** [comment]
I have not had a chance to look into this much, but I think your idea of including the date pattern in the translated strings sounds very reasonable!  

I am not super familiar with the available utilities that might already exist to solve this problem though.  So it might be worth someone doing a bit more research into how other apps handle this problem...

**Comment by le-jun** [comment]
Guess an option for a 24 h time-format would fit in this issue as well.
