### ISSUE TITLE
[Bug] Keyboard popping up in wrong places

### ISSUE THREAD

**Issue by hayribakici** [jkuester/unlauncher#127]
This bug report belongs to [2.0.0-beta.4](https://github.com/jkuester/unlauncher/releases/tag/2.0.0-beta.4)

### How to reproduce:
1. unlauncher mainFragment is shown
2. Open any app on your phone
3. Turn the phone to landscape mode
4. Turn the phone back to portrait mode
5. Press Home Key

### Expected behaviour
unlauncher mainFragment is shown

### Actual behaviour
unlauncher mainFragment is shown with a popped up keyboad.

**Comment by Nikl174** [comment]
There is also another way to reproduce this (if this is the same bug):

### How to reproduce:

1. Have Unlauncher as the default launcher and open the search ( and implicitly the keyboard) at least once
2. Launch any App and wait a few seconds
3. Go back to the Homescreen with the home butten/gesture
