### ISSUE TITLE
Request: Custom calendar app

### ISSUE THREAD

**Issue by jlnbdt** [jkuester/unlauncher#13]
Hi,

It would be interesting to be able to change the calendar app. I don’t use the default one.

Thanks for this great app!

**Comment by viniciussbs** [comment]
Hi, @jlnbdt 

Have you tried to change the default calendar app in your device settings? I haven't tried that, I'm just guessing here. I hope that helps.

**Comment by jkuester** [comment]
I just double-checked this and can confirm that Unlauncher will open your default calendar app. If you have multiple calendar apps installed you should be prompted the first time you click the date in Unlauncher to choose which calendar app you want to use as the default.  

If you want to change your default calendar app, go to the Device Settings > Apps & Notifications > See all apps. Then select the _current_ default calendar app > Open by default > Clear defaults.  Then, from the Unlauncher homescreen, tap the date and you should be prompted to choose which calendar app you would like to use.

If this does not address your issue, feel free to reopen this issue for further discussion.
