### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by isquare0** [jkuester/unlauncher#149]
Hi, Can you add the ability to add wallpaper to the launcher, I love the minimalism of the launcher, but not being able to add wallpaper is annoying (Translate)

**Comment by jkuester** [comment]
Unfortunately, an image wallpaper is not really within the intended scope or functionality of Unlauncher.  More theme customizations may be provided in the future for setting colors, fonts, etc. However, I do not intend to add support for wallpaper images.
