### ISSUE TITLE
Move "Options" Button to Right above "Apps" to prevent overdrawing

### ISSUE THREAD

**Issue by cx405** [jkuester/unlauncher#15]
One picture says thousands words: https://imgur.com/a/kiSSYPK
This happens when one sets Font size to Big or Huge (seniors do that).
Probably its better to move Options to the Right side of screen above Apps.

Maybe its would be smarter also to replace both Options and Apps with two icons, since they occupy much less space and are just two icons.

**Comment by rindeal** [comment]
long app names would still clash, it'll be better to have the buttons inside an opaque bottom app bar
