### ISSUE TITLE
Rename apps in drawer

### ISSUE THREAD

**Issue by schavi** [jkuester/unlauncher#159]
It would be great if the apps in the app drawer would be renamable as well. Nowadays every app has a silly name and it's annoying, I want to rename them to reflect their function. (eg. Firefox -> Browser; Musicolet -> Music; etc.)

(p.s.: I'm really loving this launcher, if this feature and custom font + custom colors would be added it would be absolutely perfect!)

**Comment by khwolf** [comment]
This is solved in the development version by #134 Add popup menu for apps in the drawer

**Comment by everythingeeb** [comment]
Was just about to say this. Otherwise this launcher is perfection 😁

**Comment by jkuester** [comment]
Closing since as @khwolf pointed out, this has been completed!
