### ISSUE TITLE
[Feature Request] Automatically open the app after typing its name

### ISSUE THREAD

**Issue by fusaty** [jkuester/unlauncher#175]
Hello,

Would there be interest for a feature that would automatically open the app after typing its name in "Search apps"?

When you start typing the name of the app and after it becomes the only possible option it will automatically open.

**Comment by khwolf** [comment]
I have implemented something similar to this in #158. Together with prioritizing apps that start with the searchterm in the sortring, i regularly need only 2-4 keys to start one out of more than 200 apps.

Please feel free to comment and vote on the pullrequest.

**Comment by TobiTenno** [comment]
closed w/ #158
