### ISSUE TITLE
Latest Release on F-Droid is Broken on Android 11

### ISSUE THREAD

**Issue by reverendj1** [jkuester/unlauncher#18]
Looks like something in the latest F-Droid release breaks compatibility with Android 11. None of my current shortcuts do anything, and when I click Apps to see more, only Play Store and Settings show. I believe this was an issue with Slim that was just recently fixed.

**Comment by fusion44** [comment]
Yep, it's a permission problem:
https://github.com/sduduzog/slim-launcher/pull/119

**Comment by jkuester** [comment]
Thank you for reporting this!  I just wanted to let everyone know that I hope to push an update for Unlauncher ASAP to address this issue.  Should have it out today and then it may take another day for the new version to get picked up by F-Droid.

**Comment by jkuester** [comment]
This issue should be fixed in https://github.com/jkuester/unlauncher/releases/tag/v0.1.3

This update should also be pushed to the FDroid repository soon!
