### ISSUE TITLE
Alphabetical headers in drawer do not handle apps from work profile

### ISSUE THREAD

**Issue by jkuester** [jkuester/unlauncher#188]
Work profile apps have an special unicode `W` glyph appended to the front of their name. Currently, this means that the Header will fail to generate and you will just have a missing character glyph for the header of the work apps.

I think for now it is fine to just use the `W` glyph as the header for the section (and not worry about any sub-sections within the work apps).

**Comment by TobiTenno** [comment]
I think that way makes the most sense as the header, if it'll let you use that unicode glyph w/ the box. but where should they end up in the sorting? with the normal "W"-starting apps, or at the end, like they do now?

**Comment by jkuester** [comment]
My plan was just to have them at the end in a section using the boxed `W` with the header.

**Comment by jkuester** [comment]
https://github.com/jkuester/unlauncher/pull/199
