### ISSUE TITLE
Notify when cannot unintall app

### ISSUE THREAD

**Issue by jkuester** [jkuester/unlauncher#190]
When trying to uninstall a system app from the drawer via the long-press menu, the uninstall will fail, but the user will not be notified in any way.  

It would be nice to pop a notification saying the uninstall had failed.

https://github.com/jkuester/unlauncher/blob/d9518e8b861239da8a14e5a2dab417dce097abfa/app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt#L378C17-L378C17

**Comment by hayribakici** [comment]
What if the uninstall menu is just disabled or hidden?

**Comment by jkuester** [comment]
So, some bad QA on my part :facepalm:   When I tested this again, I realized that a system notification did get popped indicating that the uninstall failed....

That being said, you are right that it would be a way better UX to just not show the option at all!
