### ISSUE TITLE
Choose Alignment Functionaltiy broken

### ISSUE THREAD

**Issue by jkuester** [jkuester/unlauncher#191]
The "Choose Alignment" functionality seems broken now.  Unfortunately one of the recently merged PRs has probably introduced a regression in this functionality.

**Comment by TobiTenno** [comment]
i'll take a look at this

**Comment by TobiTenno** [comment]
what build/android version is it not working for you on? working on a 3a, api 34 for me.

**Comment by TobiTenno** [comment]
maybe it's an emulator vs physical difference,  i've got it up on a nexus 5, api 21 as well

![image](https://github.com/jkuester/unlauncher/assets/7128721/e6af6537-0e7a-450f-b711-65d71faa3ed4)

**Comment by jkuester** [comment]
Hmm, interesting!  I was seeing this not work on emulated Android 14.  Will try to test it some more tomorrow with various devices and see if I can get a recreation pattern....

**Comment by TobiTenno** [comment]
> Hmm, interesting!  I was seeing this not work on emulated Android 14.  Will try to test it some more tomorrow with various devices and see if I can get a recreation pattern....

I was able to run it on my pixel 7 pro on android 14 as well.

**Comment by jkuester** [comment]
Okay, so funny story.  I was thinking that the alignment would affect the entire app (so home apps, apps in the drawer, and maybe even the options pages).  When I was testing this, I don't think I had added anything to the home screen so, I was just going off the apps in the drawer.  

Is it expected that the Choose Alignment setting will only affect the Home Apps?  If so, then perhaps this issue should be shifted to making the alignment more consistent across the app...

**Comment by TobiTenno** [comment]
ah, i think that would be a big difference in terms of implementation. probably not a huge refactor, but it would be different

**Comment by khwolf** [comment]
For me there is a difference between apps on the home screen and apps in the drawer. And the preferences are again a totally different thing.

The six apps on the home screen are not scrollable and alignment is more or less just optics. In the drawer they are in a list and having them aligned left (where one starts reading a line) makes finding apps a lot easier as if they were centered or right aligned. (OK, RTL-languages are different, but that would be a different thing, at least in my book).

Just my two cents...

**Comment by jkuester** [comment]
After tinkering with the alignment feature a bit, I think I agree with you!  The home screen alignment is one thing, I may want those centered, etc.  But for the options/drawer, I would not necessarily want those centered (even if I had my home screen centered).  

My current thinking is that it makes sense to keep the alignment of the home screen as fully adjustable, but then for https://github.com/jkuester/unlauncher/issues/49 we should be able to automatically shift the options pages and the app list to the other side for R2L locales...

**Comment by TobiTenno** [comment]
i think adjusting automatically for RTL locales definitely makes sense, i do feel that the drawer itself (but not options or settings pages) should be consistent w/ the home page so that swiping into the drawer isn't wholly inconsistent.

i started trying to look into auto-aligning from the language direction. i've not had much luck yet because of how app names seem to localize, but that should be an easy enough default once we get RTL locale app names to show up as the correct locale

**Comment by jkuester** [comment]
:+1: sounds good!  For eventually supporting RTL, I think we could even just load a property value from the `strings.xml` that would indicate what the default alignment should be (similar to how we have `main_date_format` now).  But we should worry about that as part of #49.

**Comment by jkuester** [comment]
https://github.com/jkuester/unlauncher/pull/200
