### ISSUE TITLE
App Drawer apps should still appear in App List

### ISSUE THREAD

**Issue by CubeOfCheese** [jkuester/unlauncher#202]
Sometimes I go to the App List and search for an app that I have in my app drawer without thinking. I would like to see the app in both places. That way if I try searching for the app in the app list without thinking, it will be there anyway. Right now I have to cancel my search and then go back to the app drawer. It would be a minor convenience

**Comment by jkuester** [comment]
Okay, so I just want to be sure I am understanding you correctly.  When you say "an app that I have in my app drawer" do you mean the 1-6 apps you have pinned to your home screen?  (Usually I call those "home apps" and then I call the app list that you swipe up into the "app drawer", but obviously there is not really any official naming....)

If so, then yes I think this is a great idea!  Really, this should have been included as a part of the "Search All Apps" functionality that was added recently (but has not been released yet).

**Comment by jkuester** [comment]
:laughing: So I just realized that I think this is already been implemented with the "Search All Apps" functionality!  So, I will go ahead and close this, but please reopen if I have misunderstood your request!
