### ISSUE TITLE
Hide apps from list

### ISSUE THREAD

**Issue by bkhl** [jkuester/unlauncher#21]
Being able to hide apps from the app list would be helpful for apps you don't want to accidentally start at all, but can't be uninstalled/disabled.

In my case, my phone comes with two apps called "Files", one of which I don't want to use, but neither is "disablable", so I'd need to remember which comes first in the list.

PS. Thanks for the app! Aside from this papercut it suits me perfectly.

**Comment by chuckcarroll** [comment]
I second this. There are redundant applications in the list such as the camera and phone. Would love to see this added. Still an amazing launcher nonetheless.

**Comment by jaredreardon** [comment]
This would be great. Having redundant apps like Gallery, Camera, etc, plus apps that are useless to have displayed like Keyboard apps, able to be hidden would be incredibly useful in decluttering the launcher!
