### ISSUE TITLE
Posting unlauncher to the Play Store

### ISSUE THREAD

**Issue by danielmehring** [jkuester/unlauncher#216]
Is there any reason it didn't get posted on the Google Play Store? In my opinion it's just a benefit because more people can you the app.

**Comment by jkuester** [comment]
Posting to the Play Store requires jumping through a few more (minor) hoops (e.g. maintaining a Google Developer account, etc).  I just do not really have any desire to go out of my way to participate in a proprietary ecosystem.  (And increasing the user-count has never really been a motivation for Unlauncher... :shrug: )

As I mentioned in https://github.com/jkuester/unlauncher/issues/75, I am open to hearing about cases where someone wants to use Unlauncher, and the Play Store is the only feasible option and possibly changing this position in the future. But for now, I am pretty happy with just distributing on F-Droid!
