### ISSUE TITLE
Analog Clock being selected when searching

### ISSUE THREAD

**Issue by GloryConway** [jkuester/unlauncher#217]
When I swipe up to go through my list of apps, if I click the search bar in the middle to look for an app the timer menu pops up from the clock. I am pretty sure this is a big. It's extremely annoying either way.

Bug

https://github.com/jkuester/unlauncher/assets/141758343/77fdac21-e0d3-4f98-9ebd-beed1957e663

Running Android 13
Running 2.1.1 from F Droid

**Comment by jkuester** [comment]
:+1: Confirming that I can re-create the behavior!  Seems like the select box for the analog clock is not being moved during the layout transition (or not moved far enough...)
