### ISSUE TITLE
How to activate lockscreen

### ISSUE THREAD

**Issue by faebser** [jkuester/unlauncher#22]
Hi, I stumbled over unlaucher after reading https://maximevaillancourt.com/blog/turning-my-smartphone-into-a-boring-tool. There is a screenshot of the lock screen further down the article.

I've installed unlaucher from f-droid and set it as my default home app. But somehow I still have the stock lock screen and not the screen shown in the screenshot. How do I activate the unlauncher lock screen?

**Comment by francescosoave** [comment]
same issue here..did you ever manage to fix it? @faebser

**Comment by faebser** [comment]
Sorry, I never heard anything or manage to fix it.

**Comment by francescosoave** [comment]
no problem, my solution so far: create a 100% black wallpaper and set that. It doesn't show the app names on unlauncher's home but at least it's black.

**Comment by jkuester** [comment]
Sorry for the delayed response here. Somehow this issue slipped past me.

As was previously mentioned, there is no lock-screen functionality included in Unlauncher.  The effect in the mentioned image was created by setting the wallpaper to a black image.  

Honestly, though, Unlauncher probably should support automatically setting the wallpaper. I have opened #54 for this enhancement.
