### ISSUE TITLE
24-hour binary clock

### ISSUE THREAD

**Issue by EGYT5453** [jkuester/unlauncher#225]
# Problem?
There are only 4 "hour" bits, which is not enough for encoding 24-hour clock ( (2 ^ 4) - 1 = 15; 15 < 23)
# My solution?
Add another bit, like here:
![A 24-hour binary clock, with 5 bits](https://upload.wikimedia.org/wikipedia/commons/1/19/Binary_clock_Swiss_railway_station.jpg)
*BBCLCD, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons*

**Comment by khwolf** [comment]
Setting time format to 24 hours should work...

**Comment by khwolf** [comment]
... but does not. Sorry and thanks for noticing!
Fixed with #229
