### ISSUE TITLE
Analoge Clock moves 1 hour behind

### ISSUE THREAD

**Issue by zickzackzuck** [jkuester/unlauncher#235]
My analog Clock runs one hour late. With the digital Clock are no Problems. 
Writing from Germany, perhaps a Problem with the time Zone?

Regards
Robert

**Comment by jkuester** [comment]
Strange!  Maybe something odd with locale or something.  :thinking: Can you let me know your settings for the following so we can try to recreate this?  

- System language
- Time zone
- Time format (12 vs 24hr)
- Android version
- Screenshot (preferably including your notification bar with the digital time displayed)

Thanks!

**Comment by zickzackzuck** [comment]
Now it works, don t know why. I will Close the Bug.

**Comment by faizanmohnavi** [comment]
Sorry to reopen this issue, but I just installed Unlauncher and I am facing this issue. 

If it is 02:45. it shows the hour hand on 02 (exactly on 02) and the minute hand on 09 (45 mins). Strange.

**Comment by jkuester** [comment]
👍  That issue we did get figured out!  😅   The fix [has been made](https://github.com/jkuester/unlauncher/pull/252), but it has not been released yet.

**Comment by faizanmohnavi** [comment]
Looking forward to the update. Great work!
