### ISSUE TITLE
Add an option to choose alignment of app lists

### ISSUE THREAD

**Issue by rindeal** [jkuester/unlauncher#26]
Currently, both lists are left aligned, I'd like them right aligned or centred.

**Comment by francescosoave** [comment]
yes please..apps on the right would make it much more one-hand usable, thanks!

**Comment by Donkey-Doug** [comment]
Perhaps use the orientation sensor to allow the user to tilt the device slightly to align all apps either left or right?

**Comment by TobiTenno** [comment]
closed w/ #161
