### ISSUE TITLE
Swipe down from anywhere to open notification panel

### ISSUE THREAD

**Issue by iwconfig** [jkuester/unlauncher#30]
Nice laucher! The only thing I'm really missing is the ability to view my notifications and quick controls by swiping down from anywhere on the screen, both when the statusbar is hidden and when it's not.

**Comment by Donkey-Doug** [comment]
I agree. Definetly a missing feature.

**Comment by JM480** [comment]
This feature would be very helpful for devices with large screens.

**Comment by Charles7z** [comment]
This is a must have for me 😭
