### ISSUE TITLE
Swipe up twice for the app drawer

### ISSUE THREAD

**Issue by iwconfig** [jkuester/unlauncher#31]
Wait, there's one more thing I'm missing! I like the 7 favorite apps list that shows up when I swipe upwards once. It would be nice if I could swipe upwards once again, when the 7 favorite apps are visible, to open the whole app drawer.

I think this way is much more intuitive than having to reach the bottom right corner with my thumb! :smile_cat::100:

**Comment by jkuester** [comment]
Agreed!  :+1:  This is behaviour that I would like to add as part of #1.
