### ISSUE TITLE
Theming?

### ISSUE THREAD

**Issue by shelbyKiraM** [jkuester/unlauncher#32]
I want to make it Dracula themed but I'm unsure what needs to be modified on my fork...

Also, the ability to pick a font would be nice.

**Comment by shelbyKiraM** [comment]
Here's the colour palette: https://github.com/dracula/dracula-theme

**Comment by jkuester** [comment]
Support for changing the font is definitely something we want to add in the future!  https://github.com/jkuester/unlauncher/issues/8

Regarding adding a new theme, I think all you would need to do is update the [style.xml](https://github.com/jkuester/unlauncher/blob/master/app/src/main/res/values/styles.xml) with your new color palette (any new color values can be added to the [colors.xml](https://github.com/jkuester/unlauncher/blob/master/app/src/main/res/values/colors.xml).  Then add a reference to your new style here: https://github.com/jkuester/unlauncher/blob/912e48f6785367a55a607d57e6ff06b3f5986334/app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt#L126

Finally, the last thing to do would be to add the name of your theme to the [string.xml](https://github.com/jkuester/unlauncher/blob/912e48f6785367a55a607d57e6ff06b3f5986334/app/src/main/res/values/strings.xml#L7).

If you get something put together that you like, feel free to open a PR here to add the new theme!
