### ISSUE TITLE
Support for hiding Unlauncher 'settings' button

### ISSUE THREAD

**Issue by tvlpirb** [jkuester/unlauncher#36]
Before the update to access the launcher settings you had to swipe up and then tap options, the new update adds a button directly on the main screen which is a minor annoyance aesthetically and the button is hardly used. 

A suggestion would be to hide the button and make it visible when holding down on the screen. What do you think?
![Screenshot_20210212-132610__02](https://user-images.githubusercontent.com/22998573/107758731-5d8c3d00-6d38-11eb-9f37-3e76fd87a640.jpg)

**Comment by jkuester** [comment]
Yes!  I actually meant to log an issue for this myself. Ideally I would like to just add a setting so that users could chose between having the button or just long-pressing on the screen to access the settings.  I hope to get something put together for this in the near future, but would happily accept a PR for these changes if anyone else has the time.

**Comment by TobiTenno** [comment]
long press sounds more useable, and i guess that would work to just remove this entirely, right? similar to slim and some other minimal launchers?

**Comment by tvlpirb** [comment]
@jkuester That would be appreciated!

**Comment by tvlpirb** [comment]
> long press sounds more useable, and i guess that would work to just remove this entirely, right? similar to slim and some other minimal launchers?

Yes that's correct, it also makes more sense since the button is hardly used once you initially set everything up.

**Comment by TobiTenno** [comment]
> > long press sounds more useable, and i guess that would work to just remove this entirely, right? similar to slim and some other minimal launchers?
> 
> Yes that's correct, it also makes more sense since the button is hardly used once you initially set everything up.

my only concern on only doing it that way is that there's not like a readme or anything where people can see exactly how to do settings, so they might just be lost on a blank screen and insta-uninstall.

**Comment by tvlpirb** [comment]
> > > long press sounds more useable, and i guess that would work to just remove this entirely, right? similar to slim and some other minimal launchers?
> > 
> > 
> > Yes that's correct, it also makes more sense since the button is hardly used once you initially set everything up.
> 
> my only concern on only doing it that way is that there's not like a readme or anything where people can see exactly how to do settings, so they might just be lost on a blank screen and insta-uninstall.

I don't think it should be much of a concern since it's intuitive to hold on the screen like most launchers. If we look at slim launcher and other launchers which do this, their growth doesn't seem hampered. Although I do see where some people may go wrong, most users who install a custom launcher would know. 

However I could come up with two different ways of solving this:
1. There could be a guided tutorial for first time setup.
> I would like to just add a setting so that users could choose between having the button or just long-pressing on the screen to access the settings
2. The button can be toggled as Joshua mentioned above.

**Comment by Cwpute** [comment]
A toggleable option in the settings is the most easy to implement and definitely less intrusive than a tutorial !
Pewple who don't care will not go into the settngs, people who do simply will and toggle it off.

**Comment by jkuester** [comment]
I am currently working on supporting the ability in the settings to toggle the visibility of any of the 3 quick buttons (options, phone, camera).  This feature should be in the next release.  In the future I hope to be able to expand the settings for these quick buttons to support more customizations like those mentioned in https://github.com/jkuester/unlauncher/issues/23.
