### ISSUE TITLE
Search box below apps list

### ISSUE THREAD

**Issue by alfonsodelavega** [jkuester/unlauncher#43]
Hello,

Great launcher, thank you for your work!

It might be useful to allow placing the "Search apps" box of the app drawer at the bottom instead of on top, that way it could be easier to tap it to type the name of an app (just like the new Firefox for Android versions have been doing recently).

Thanks again!

**Comment by Donkey-Doug** [comment]
So in total we have a few related issues:

- Hide search field (https://github.com/jkuester/unlauncher/issues/62)
- Show at the bottom (This issue - https://github.com/jkuester/unlauncher/issues/43)
- Auto-enable keyboard (https://github.com/jkuester/unlauncher/issues/47)
