### ISSUE TITLE
Set device wallpaper to Unlanucher theme's background color

### ISSUE THREAD

**Issue by jkuester** [jkuester/unlauncher#54]
During normal interaction with a device, there are several places where the device's wallpaper is still visible (e.g. the lockscreen, #22).  It would make for a much cleaner, end-to-end experience if Unlauncher would set the device's wallpaper to match the background color from the Unlauncher theme.

**Comment by jkuester** [comment]
https://stackoverflow.com/questions/20053919/programmatically-set-android-phones-background

**Comment by hayribakici** [comment]
@jkuester I wonder if the app should ask the user if the wallpaper should be changed on initial startup or when it is set as the device's main launcher?
