### ISSUE TITLE
Long-pressing in app list

### ISSUE THREAD

**Issue by Donkey-Doug** [jkuester/unlauncher#69]
Long-pressing in the app list should not open the launcher settings.

**Comment by ccptr** [comment]
It feels really awkward having to open system settings and navigating to an app's info just to toggle a permission, force stop it, etc.. If I need to access the launcher settings I can long press on the home screen or maybe an empty space (like to the right of the app name?)

**Comment by jkuester** [comment]
:+1: @ccptr I agree.  Seems like it might be good to have a long-press on the app actually trigger a small menu to let the user choose what they want: 

- Open app (maybe the long-press was unintentional)
- Open app settings (this could open the app in the system settings)
- Rename app
- Open Unlauncher Options

**Comment by Charles7z** [comment]
Olauncher does this a little — long press on app in app drawer and you get "hide" and info icon. I think adding a pencil icon to edit the name and a trash can to uninstall would be good!

No open app, re-tapping the app toggles it back to normal, see how Olauncher implemented it, they did a good job.

I don't think users need an opinion on an app to open Unlauncher options, long press on home screen is all that most launcher apps use to get to their options.

**Comment by jkuester** [comment]
Closed by https://github.com/jkuester/unlauncher/pull/134
