### ISSUE TITLE
Quick Buttons

### ISSUE THREAD

**Issue by ja7833** [jkuester/unlauncher#94]
I enjoy the minimalism of unlauncher.  The phone app is ironically one of my least used apps on my phone.  Would it be possible to customize with a couple of other icon choices and select the app that opens?

e.g. Phone icon but open Signal, Chat icon that opens Messages, Sun icon that opens weather etc.

I don't want to hide the quick buttons on the home screen; I want to replace them with apps I use more frequently than the six named apps you can customize.

Thanks for the consideration.

**Comment by jkuester** [comment]
Yes! This is exactly my long-term vision with those Quick Buttons! The bad news is that no one has implemented this yet (PR's welcome!).  The good news is that recently I finished overhauling the back-end data storage for the app to make it **much** easier to add functionality like this, so I am optimistic we will get this done in the near future.

Progress for this feature will be tracked over on https://github.com/jkuester/unlauncher/issues/23.
