### ISSUE TITLE
[Feature Request] Add seperator line by first letter on app listing

### ISSUE THREAD

**Issue by bserem** [jkuester/unlauncher#98]
UX would be greatly improved if apps get seperated by letter with an extra line:
![image](https://user-images.githubusercontent.com/520237/144724062-72440f1d-b94b-454e-8c4f-85a4234f6d8c.png)

Extra bonus, allow to click on a letter to quickly jump on another one with a letter pad.
Crazy as it may sound, I believe that Microsoft nailed it with Windows Phone and their app listing:
![image](https://user-images.githubusercontent.com/520237/144724049-09938fd9-dba5-4cb7-b350-a517f5179b0b.png)

Hope you like the idea and have a look on it.

**Comment by jkuester** [comment]
I like this idea!  (And +1 for the example screenshots from the Windows Phone! That is priceless!)  :laughing:
