### ISSUE TITLE
Open the Top of the App List Every Time App List is Opened

### ISSUE THREAD

**Issue by jaredreardon** [jkuester/unlauncher#99]
Currently, if you swipe up and open the app list and you click on an app, for example, in the middle of the screen and go back home and reopen your app list, it will open at the place where the previous app you opened was, in this case the middle of your app list. Personally, I find this behavior to be quite annoying and disruptive to what I expect when opening my list of apps. Video of the behavior attached below.

https://user-images.githubusercontent.com/67240033/147613259-1d3aa572-5370-4191-8b1e-a60e61b05791.mp4

**Comment by jkuester** [comment]
Yes, this issue needs to be fixed.  I think this is a duplicate of https://github.com/jkuester/unlauncher/issues/70
